/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import type { Stat } from '../types';
// FIX: Import 'CRAFTING_TAGS' to resolve reference errors.
import { ITEM_TAGS, ELEMENTAL_TAGS, CRAFTING_TAGS } from './tagConstants';

// The template defines all properties of a stat except its unique ID and final description.
export type ItemTemplate = Omit<Stat, 'id' | 'description'> & {
    baseDescription: string;
};

export const BASE_ITEM_TEMPLATES: Record<string, ItemTemplate> = {
    // --- TRANG PHỤC THƯỜNG NGÀY & THỜI TRANG ---
    'Áo Sơ Mi Trắng': {
        name: 'Áo Sơ Mi Trắng',
        baseDescription: 'Một chiếc áo sơ mi trắng đơn giản, sạch sẽ và lịch sự.',
        category: 'Vật phẩm',
        slot: 'Thân trên',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC],
        rarity: 'Phổ thông',
        price: 20,
    },
    'Quần Jean Xanh': {
        name: 'Quần Jean Xanh',
        baseDescription: 'Một chiếc quần jean xanh cổ điển, bền và thoải mái.',
        category: 'Vật phẩm',
        slot: 'Thân dưới',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC],
        rarity: 'Phổ thông',
        price: 30,
    },
    'Giày Thể Thao': {
        name: 'Giày Thể Thao',
        baseDescription: 'Một đôi giày thể thao nhẹ và êm ái, phù hợp cho việc đi lại hàng ngày.',
        category: 'Vật phẩm',
        slot: 'Giày',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC],
        rarity: 'Phổ thông',
        price: 40,
    },
    'Váy dạ hội': {
        name: 'Váy dạ hội',
        baseDescription: 'Một chiếc váy dạ hội lộng lẫy, được thiết kế tinh xảo, phù hợp cho các buổi tiệc sang trọng.',
        category: 'Vật phẩm',
        slot: 'Thân trên',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC],
        rarity: 'Hiếm',
        price: 200,
    },
    'Quần lót nam': {
        name: 'Quần lót nam',
        baseDescription: 'Một chiếc quần lót nam cơ bản, sạch sẽ.',
        category: 'Vật phẩm',
        slot: 'Quần Lót',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, ITEM_TAGS.MISC_TYPE.LINGERIE, 'nam'],
        rarity: 'Phổ thông',
        price: 15,
    },
    'Đồ lót ren': {
        name: 'Đồ lót ren',
        baseDescription: 'Một bộ đồ lót ren mỏng manh và gợi cảm.',
        category: 'Vật phẩm',
        slot: 'Áo Lót',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, ITEM_TAGS.MISC_TYPE.LINGERIE, 'nữ'],
        rarity: 'Cao cấp',
        price: 50,
    },
    'Áo Ba Lỗ': {
        name: 'Áo Ba Lỗ',
        baseDescription: 'Một chiếc áo ba lỗ cotton, thường được mặc lót bên trong để thấm hút mồ hôi.',
        category: 'Vật phẩm',
        slot: 'Áo Lót',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, ITEM_TAGS.MISC_TYPE.LINGERIE, 'nam'],
        rarity: 'Phổ thông',
        price: 20,
    },
    'Áo Thun Lót': {
        name: 'Áo Thun Lót',
        baseDescription: 'Một chiếc áo thun mỏng, mặc bên trong áo sơ mi để tạo sự thoải mái.',
        category: 'Vật phẩm',
        slot: 'Áo Lót',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, ITEM_TAGS.MISC_TYPE.LINGERIE, 'nam'],
        rarity: 'Phổ thông',
        price: 25,
    },
    'Bộ đồ tắm': {
        name: 'Bộ đồ tắm',
        baseDescription: 'Một bộ đồ bơi phù hợp cho các hoạt động dưới nước.',
        category: 'Vật phẩm',
        slot: 'Quần Lót',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, ITEM_TAGS.MISC_TYPE.SWIMSUIT],
        rarity: 'Phổ thông',
        price: 50,
    },
    'Tất Chân Lưới': {
        name: 'Tất Chân Lưới',
        baseDescription: 'Một đôi tất chân dạng lưới, gợi cảm và táo bạo.',
        category: 'Vật phẩm',
        slot: 'Phụ Kiện chân',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, ITEM_TAGS.MISC_TYPE.STOCKINGS],
        rarity: 'Cao cấp',
        price: 35,
    },
    'Áo Khoác Da': {
        name: 'Áo Khoác Da',
        baseDescription: 'Một chiếc áo khoác da màu đen, mang lại vẻ ngoài sành điệu và một chút nổi loạn.',
        category: 'Vật phẩm',
        slot: 'Thân ngoài',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, ITEM_TAGS.ORIGIN.MODERN],
        rarity: 'Cao cấp',
        price: 150,
    },
    'Áo Hoodie': {
        name: 'Áo Hoodie',
        baseDescription: 'Một chiếc áo nỉ có mũ trùm đầu, thoải mái và ấm áp.',
        category: 'Vật phẩm',
        slot: 'Thân trên',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, ITEM_TAGS.ORIGIN.MODERN],
        rarity: 'Phổ thông',
        price: 60,
    },
    'Quần Kaki': {
        name: 'Quần Kaki',
        baseDescription: 'Một chiếc quần kaki lịch sự, phù hợp cho cả đi làm và đi chơi.',
        category: 'Vật phẩm',
        slot: 'Thân dưới',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, ITEM_TAGS.ORIGIN.MODERN],
        rarity: 'Phổ thông',
        price: 50,
    },
    'Chân Váy Ngắn': {
        name: 'Chân Váy Ngắn',
        baseDescription: 'Một chiếc chân váy ngắn trẻ trung và năng động.',
        category: 'Vật phẩm',
        slot: 'Thân dưới',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, ITEM_TAGS.ORIGIN.MODERN],
        rarity: 'Phổ thông',
        price: 45,
    },
    'Giày Cao Gót': {
        name: 'Giày Cao Gót',
        baseDescription: 'Một đôi giày cao gót thanh lịch, tôn lên vóc dáng của người phụ nữ.',
        category: 'Vật phẩm',
        slot: 'Giày',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, ITEM_TAGS.ORIGIN.MODERN],
        rarity: 'Cao cấp',
        price: 180,
    },
    'Bộ Vest Lịch Lãm': {
        name: 'Bộ Vest Lịch Lãm',
        baseDescription: 'Một bộ áo vest được may đo cẩn thận, thể hiện sự chuyên nghiệp và đẳng cấp.',
        category: 'Vật phẩm',
        slot: 'Thân ngoài',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, ITEM_TAGS.ORIGIN.MODERN],
        rarity: 'Hiếm',
        price: 400,
    },
    'Quần Tây': {
        name: 'Quần Tây',
        baseDescription: 'Một chiếc quần tây ống đứng, là một phần của bộ vest lịch lãm.',
        category: 'Vật phẩm',
        slot: 'Thân dưới',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, ITEM_TAGS.ORIGIN.MODERN],
        rarity: 'Hiếm',
        price: 150,
    },
    
    // --- ĐỒNG PHỤC ---
    'Đồng phục Học sinh (Áo sơ mi)': {
        name: 'Đồng phục Học sinh (Áo sơ mi)',
        baseDescription: 'Áo sơ mi trắng, một phần của bộ đồng phục học sinh.',
        category: 'Vật phẩm',
        slot: 'Thân trên',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, 'đồng phục'],
        rarity: 'Phổ thông',
        price: 25,
    },
    'Đồng phục Học sinh (Chân váy)': {
        name: 'Đồng phục Học sinh (Chân váy)',
        baseDescription: 'Chân váy xếp ly màu xanh nước biển, một phần của bộ đồng phục học sinh nữ.',
        category: 'Vật phẩm',
        slot: 'Thân dưới',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, 'đồng phục'],
        rarity: 'Phổ thông',
        price: 30,
    },
    'Đồng phục Học sinh (Quần tây)': {
        name: 'Đồng phục Học sinh (Quần tây)',
        baseDescription: 'Quần tây màu xanh nước biển, một phần của bộ đồng phục học sinh nam.',
        category: 'Vật phẩm',
        slot: 'Thân dưới',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, 'đồng phục'],
        rarity: 'Phổ thông',
        price: 30,
    },
    'Áo đồng phục Cảnh sát': {
        name: 'Áo đồng phục Cảnh sát',
        baseDescription: 'Áo đồng phục tiêu chuẩn của lực lượng cảnh sát, có phù hiệu.',
        category: 'Vật phẩm',
        slot: 'Thân trên',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, 'đồng phục'],
        effects: [{ targetStat: 'Uy tín', modifier: '+10' }],
        rarity: 'Cao cấp',
        price: 100,
    },
    'Quần đồng phục Cảnh sát': {
        name: 'Quần đồng phục Cảnh sát',
        baseDescription: 'Quần đồng phục tiêu chuẩn của lực lượng cảnh sát.',
        category: 'Vật phẩm',
        slot: 'Thân dưới',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, 'đồng phục'],
        rarity: 'Cao cấp',
        price: 80,
    },
    'Áo bảo hộ Lính cứu hỏa': {
        name: 'Áo bảo hộ Lính cứu hỏa',
        baseDescription: 'Một chiếc áo khoác dày, chống cháy, được thiết kế để bảo vệ lính cứu hỏa khỏi nhiệt độ cao.',
        category: 'Vật phẩm',
        slot: 'Thân ngoài',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, 'đồng phục', ITEM_TAGS.FUNCTIONALITY.DEFENSE],
        effects: [{ targetStat: 'Kháng Hỏa', modifier: '+80%' }],
        rarity: 'Hiếm',
        price: 500,
    },
    'Quần bảo hộ Lính cứu hỏa': {
        name: 'Quần bảo hộ Lính cứu hỏa',
        baseDescription: 'Một chiếc quần bảo hộ dày, chống cháy.',
        category: 'Vật phẩm',
        slot: 'Thân dưới',
        tags: [ITEM_TAGS.FUNCTIONALITY.COSMETIC, 'đồng phục', ITEM_TAGS.FUNCTIONALITY.DEFENSE],
        rarity: 'Hiếm',
        price: 400,
    },

    // --- KHIÊN ---
    'Khiên Tháp': {
        name: 'Khiên Tháp',
        baseDescription: 'Một chiếc khiên lớn và nặng, cung cấp khả năng phòng thủ tuyệt vời nhưng làm giảm sự linh hoạt.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.ONE_HANDED, ITEM_TAGS.WEAPON_TYPE.SHIELD, ITEM_TAGS.FUNCTIONALITY.DEFENSE, ITEM_TAGS.ORIGIN.FANTASY],
        effects: [{ targetStat: 'Phòng Thủ', modifier: '+30' }, { targetStat: 'Tốc Độ', modifier: '-5' }],
        rarity: 'Hiếm',
        price: 600,
    },

    // --- VŨ KHÍ CỔ ĐẠI & TRUNG CỔ ---
    'Kiếm Sắt': {
        name: 'Kiếm Sắt',
        baseDescription: 'Một thanh kiếm sắt cơ bản, được rèn tốt, sắc bén và đáng tin cậy cho một nhà thám hiểm mới bắt đầu.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.ONE_HANDED, ITEM_TAGS.WEAPON_TYPE.SWORD, ITEM_TAGS.FUNCTIONALITY.MELEE, ITEM_TAGS.ORIGIN.MARTIAL_ARTS, ITEM_TAGS.MATERIAL_TYPE.METAL],
        effects: [{ targetStat: 'Tấn Công', modifier: '+5' }],
        rarity: 'Phổ thông',
        price: 15,
    },
    'Trường Cung Gỗ': {
        name: 'Trường Cung Gỗ',
        baseDescription: 'Một cây cung dài làm từ gỗ dẻ gai, tầm bắn khá và lực vừa phải.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.TWO_HANDED, ITEM_TAGS.WEAPON_TYPE.BOW, ITEM_TAGS.FUNCTIONALITY.RANGED, ITEM_TAGS.ORIGIN.MARTIAL_ARTS, ITEM_TAGS.MATERIAL_TYPE.WOOD],
        effects: [{ targetStat: 'Tấn Công', modifier: '+7' }],
        rarity: 'Phổ thông',
        price: 20,
    },
    'Mũi Tên Sắt': {
        name: 'Mũi Tên Sắt',
        baseDescription: 'Một mũi tên sắt thông thường, được làm để xuyên qua giáp nhẹ.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.WEAPON_TYPE.ARROW],
        quantity: 20,
        price: 1,
        rarity: 'Phổ thông',
    },
    'Kiếm Katana': {
        name: 'Kiếm Katana',
        baseDescription: 'Một thanh kiếm samurai truyền thống với lưỡi cong đặc trưng, nổi tiếng về độ sắc bén và tốc độ.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.ONE_HANDED, ITEM_TAGS.WEAPON_TYPE.SWORD, ITEM_TAGS.FUNCTIONALITY.MELEE, ITEM_TAGS.ORIGIN.MARTIAL_ARTS, ITEM_TAGS.MATERIAL_TYPE.METAL],
        effects: [{ targetStat: 'Tấn Công', modifier: '+12' }, { targetStat: 'Tốc Độ', modifier: '+2' }],
        rarity: 'Cao cấp',
        price: 150,
    },
    'Thương Yari': {
        name: 'Thương Yari',
        baseDescription: 'Một ngọn giáo dài của Nhật Bản, hiệu quả trong việc giữ khoảng cách với kẻ thù.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.TWO_HANDED, ITEM_TAGS.WEAPON_TYPE.SPEAR, ITEM_TAGS.FUNCTIONALITY.MELEE, ITEM_TAGS.ORIGIN.MARTIAL_ARTS, ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.MATERIAL_TYPE.WOOD],
        effects: [{ targetStat: 'Tấn Công', modifier: '+10' }],
        rarity: 'Phổ thông',
        price: 80,
    },
    'Naginata': {
        name: 'Naginata',
        baseDescription: 'Một loại vũ khí cán dài với lưỡi cong ở đầu, kết hợp tầm với của giáo và khả năng chém của kiếm.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.TWO_HANDED, ITEM_TAGS.WEAPON_TYPE.POLEARM, ITEM_TAGS.FUNCTIONALITY.MELEE, ITEM_TAGS.ORIGIN.MARTIAL_ARTS, ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.MATERIAL_TYPE.WOOD],
        effects: [{ targetStat: 'Tấn Công', modifier: '+11' }],
        rarity: 'Cao cấp',
        price: 120,
    },
    'Búa Chiến Viking': {
        name: 'Búa Chiến Viking',
        baseDescription: 'Một chiếc búa chiến một tay, nặng và mạnh mẽ, có khả năng xuyên thủng giáp nhẹ.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.ONE_HANDED, ITEM_TAGS.WEAPON_TYPE.HAMMER, ITEM_TAGS.FUNCTIONALITY.MELEE, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.MATERIAL_TYPE.METAL],
        effects: [{ targetStat: 'Tấn Công', modifier: '+9' }],
        rarity: 'Phổ thông',
        price: 70,
    },
    'Đại Kiếm Zweihänder': {
        name: 'Đại Kiếm Zweihänder',
        baseDescription: 'Một thanh đại kiếm khổng lồ của Đức, đòi hỏi sức mạnh cực lớn để sử dụng nhưng có sức công phá kinh hoàng.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.TWO_HANDED, ITEM_TAGS.WEAPON_TYPE.GREATSWORD, ITEM_TAGS.FUNCTIONALITY.MELEE, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.MATERIAL_TYPE.METAL],
        effects: [{ targetStat: 'Tấn Công', modifier: '+18' }],
        rarity: 'Hiếm',
        price: 350,
    },

    // --- VŨ KHÍ HIỆN ĐẠI ---
    'Súng Lục Glock 19': {
        name: 'Súng Lục Glock 19',
        baseDescription: 'Một khẩu súng lục bán tự động phổ biến, đáng tin cậy và cân bằng.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.ONE_HANDED, ITEM_TAGS.GUN_TYPE.PISTOL, ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.FUNCTIONALITY.RANGED],
        effects: [{ targetStat: 'Tấn Công', modifier: '+25' }],
        rarity: 'Cao cấp',
        price: 500,
    },
    'Đạn Súng Lục 9mm': {
        name: 'Đạn Súng Lục 9mm',
        baseDescription: 'Một hộp đạn 9mm tiêu chuẩn, phổ biến cho nhiều loại súng lục và tiểu liên.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.WEAPON_TYPE.AMMUNITION, ITEM_TAGS.ORIGIN.MODERN],
        quantity: 30,
        price: 30,
        rarity: 'Phổ thông',
    },
    'Đạn Súng Trường 7.62mm': {
        name: 'Đạn Súng Trường 7.62mm',
        baseDescription: 'Một hộp đạn 7.62mm mạnh mẽ, được sử dụng cho các loại súng trường tấn công như AK-47.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.WEAPON_TYPE.AMMUNITION, ITEM_TAGS.ORIGIN.MODERN],
        quantity: 30,
        price: 50,
        rarity: 'Phổ thông',
    },
    'Súng Trường AK-47': {
        name: 'Súng Trường AK-47',
        baseDescription: 'Một khẩu súng trường tấn công huyền thoại, nổi tiếng về độ bền và hỏa lực mạnh mẽ trong mọi điều kiện.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.TWO_HANDED, ITEM_TAGS.GUN_TYPE.RIFLE, ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.FUNCTIONALITY.RANGED],
        effects: [{ targetStat: 'Tấn Công', modifier: '+40' }],
        rarity: 'Hiếm',
        price: 1200,
    },
    'Súng Bắn Tỉa AWM': {
        name: 'Súng Bắn Tỉa AWM',
        baseDescription: 'Một khẩu súng bắn tỉa uy lực, có khả năng hạ gục mục tiêu từ khoảng cách cực xa với độ chính xác cao.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.TWO_HANDED, ITEM_TAGS.GUN_TYPE.SNIPER, ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.FUNCTIONALITY.RANGED],
        effects: [{ targetStat: 'Tấn Công', modifier: '+65' }],
        rarity: 'Sử thi',
        price: 5000,
    },
    'Shotgun Mossberg 500': {
        name: 'Shotgun Mossberg 500',
        baseDescription: 'Một khẩu shotgun cực kỳ hiệu quả ở tầm gần, có khả năng gây sát thương lớn trên diện rộng.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.TWO_HANDED, ITEM_TAGS.GUN_TYPE.SHOTGUN, ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.FUNCTIONALITY.MELEE, ITEM_TAGS.FUNCTIONALITY.AOE],
        effects: [{ targetStat: 'Tấn Công', modifier: '+50' }],
        rarity: 'Hiếm',
        price: 900,
    },
    'Dao Găm Chiến Thuật': {
        name: 'Dao Găm Chiến Thuật',
        baseDescription: 'Một con dao găm sắc bén, nhẹ và linh hoạt, lý tưởng cho các cuộc tấn công bất ngờ hoặc cận chiến.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.ONE_HANDED, ITEM_TAGS.WEAPON_TYPE.DAGGER, ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.FUNCTIONALITY.MELEE],
        effects: [{ targetStat: 'Tấn Công', modifier: '+10' }],
        rarity: 'Cao cấp',
        price: 150,
    },

    // --- GIÁP & TRANG BỊ HIỆN ĐẠI ---
    'Áo Chống Đạn': {
        name: 'Áo Chống Đạn',
        baseDescription: 'Một chiếc áo giáp nhẹ, được làm từ vật liệu Kevlar, có khả năng giảm đáng kể sát thương từ đạn súng lục.',
        category: 'Vật phẩm',
        slot: 'Thân ngoài',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.LIGHT_ARMOR, ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.FUNCTIONALITY.DEFENSE],
        effects: [{ targetStat: 'Giảm Sát Thương', modifier: '+25%' }],
        rarity: 'Cao cấp',
        price: 300,
    },

    // --- VŨ KHÍ FANTASY ---
    'Cung Thần Tộc Elf': {
        name: 'Cung Thần Tộc Elf',
        baseDescription: 'Một cây cung được chế tác từ gỗ Yggdrasil, nhẹ và thanh thoát, có khả năng bắn ra những mũi tên được yểm bùa gió.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.TWO_HANDED, ITEM_TAGS.WEAPON_TYPE.BOW, ELEMENTAL_TAGS.EXTENDED_ELEMENTS.WIND, ITEM_TAGS.FUNCTIONALITY.RANGED, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.MATERIAL_TYPE.WOOD],
        effects: [{ targetStat: 'Tấn Công', modifier: '+20' }, { targetStat: 'Nhanh nhẹn', modifier: '+5' }],
        rarity: 'Hiếm',
        price: 800,
    },
    'Rìu Chiến Người Lùn': {
        name: 'Rìu Chiến Người Lùn',
        baseDescription: 'Một chiếc rìu chiến được rèn trong lòng núi, nặng trịch và được khắc cổ ngữ sức mạnh, có khả năng xuyên thủng mọi loại giáp trụ.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.ONE_HANDED, ITEM_TAGS.WEAPON_TYPE.AXE, ITEM_TAGS.FUNCTIONALITY.MELEE, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.MATERIAL_TYPE.METAL],
        effects: [{ targetStat: 'Tấn Công', modifier: '+18' }, { targetStat: 'Phòng Thủ', modifier: '+3' }],
        rarity: 'Hiếm',
        price: 750,
    },
    'Thánh Kiếm Ánh Sáng': {
        name: 'Thánh Kiếm Ánh Sáng',
        baseDescription: 'Một thanh kiếm tỏa ra ánh sáng thánh khiết, là khắc tinh của bóng tối và các sinh vật hắc ám.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.ONE_HANDED, ITEM_TAGS.WEAPON_TYPE.SWORD, ELEMENTAL_TAGS.MAGIC_TYPE.HOLY, ITEM_TAGS.FUNCTIONALITY.MELEE, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.FUNCTIONALITY.BLESSED, ITEM_TAGS.MATERIAL_TYPE.METAL],
        effects: [{ targetStat: 'Tấn Công', modifier: '+30' }, { targetStat: 'Sát thương Ám', modifier: '+25%' }],
        rarity: 'Sử thi',
        price: 3000,
    },
    'Quyền Trượng Hỏa Cầu': {
        name: 'Quyền Trượng Hỏa Cầu',
        baseDescription: 'Cây quyền trượng có gắn một viên hồng ngọc rực cháy, cho phép người sử dụng thi triển phép thuật Hỏa Cầu.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.ONE_HANDED, ITEM_TAGS.WEAPON_TYPE.STAFF, ELEMENTAL_TAGS.FIVE_ELEMENTS.FIRE, ELEMENTAL_TAGS.MAGIC_TYPE.MAGIC, ITEM_TAGS.FUNCTIONALITY.RANGED, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.MATERIAL_TYPE.WOOD],
        effects: [{ targetStat: 'Trí tuệ', modifier: '+10' }],
        rarity: 'Hiếm',
        price: 1200,
    },
    'Ma Kiếm Hút Hồn': {
        name: 'Ma Kiếm Hút Hồn',
        baseDescription: 'Lưỡi kiếm màu đen tuyền thì thầm những lời nguyền rủa, có khả năng hút sinh lực của kẻ địch để chữa lành cho chủ nhân.',
        category: 'Vật phẩm',
        slot: 'Vũ khí',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.ONE_HANDED, ITEM_TAGS.WEAPON_TYPE.SWORD, ELEMENTAL_TAGS.MAGIC_TYPE.DEMONIC, ITEM_TAGS.FUNCTIONALITY.MELEE, 'lifesteal-15', ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.FUNCTIONALITY.CURSED, ITEM_TAGS.MATERIAL_TYPE.METAL],
        effects: [{ targetStat: 'Tấn Công', modifier: '+25' }],
        rarity: 'Sử thi',
        price: 4500,
    },

    // --- GIÁP & TRANG BỊ NÂNG CAO ---
    'Giáp Da': {
        name: 'Giáp Da',
        baseDescription: 'Một bộ giáp làm từ da thú đã qua xử lý, nhẹ và linh hoạt nhưng khả năng bảo vệ có hạn.',
        category: 'Vật phẩm',
        slot: 'Thân trên',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.LIGHT_ARMOR, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.ORIGIN.MARTIAL_ARTS, ITEM_TAGS.MATERIAL_TYPE.LEATHER],
        effects: [{ targetStat: 'Phòng Thủ', modifier: '+8' }],
        rarity: 'Phổ thông',
        price: 25,
    },
    'Mũ Sắt': {
        name: 'Mũ Sắt',
        baseDescription: 'Một chiếc mũ sắt đơn giản, giúp bảo vệ đầu khỏi những đòn tấn công cơ bản.',
        category: 'Vật phẩm',
        slot: 'Mũ',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.HEAVY_ARMOR, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.ORIGIN.MARTIAL_ARTS, ITEM_TAGS.MATERIAL_TYPE.METAL],
        effects: [{ targetStat: 'Phòng Thủ', modifier: '+5' }],
        rarity: 'Phổ thông',
        price: 10,
    },
     'Balo Da Thú': {
        name: 'Balo Da Thú',
        baseDescription: 'Một chiếc balo chắc chắn làm từ da thú, có thể chứa được nhiều vật phẩm. Trang bị vào ô Áo choàng.',
        category: 'Vật phẩm',
        slot: 'Áo choàng',
        tags: [ITEM_TAGS.MISC_TYPE.BAG, ITEM_TAGS.MATERIAL_TYPE.LEATHER],
        inventoryBonus: 20,
        rarity: 'Phổ thông',
        price: 50,
    },
    'Giáp Vảy Rồng': {
        name: 'Giáp Vảy Rồng',
        baseDescription: 'Một bộ giáp được chế tác từ vảy rồng, cực kỳ cứng chắc và có khả năng kháng lửa tuyệt vời.',
        category: 'Vật phẩm',
        slot: 'Thân trên',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.HEAVY_ARMOR, ITEM_TAGS.ORIGIN.FANTASY, ELEMENTAL_TAGS.FIVE_ELEMENTS.FIRE],
        effects: [{ targetStat: 'Phòng Thủ', modifier: '+100' }, { targetStat: 'Kháng Hỏa', modifier: '+50%' }],
        rarity: 'Huyền thoại',
        price: 25000,
    },
    'Áo Choàng Bóng Tối': {
        name: 'Áo Choàng Bóng Tối',
        baseDescription: 'Một chiếc áo choàng dệt từ bóng đêm, giúp người mặc hòa lẫn vào bóng tối và di chuyển nhanh nhẹn hơn.',
        category: 'Vật phẩm',
        slot: 'Áo choàng',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.LIGHT_ARMOR, ITEM_TAGS.ORIGIN.FANTASY, ELEMENTAL_TAGS.EXTENDED_ELEMENTS.DARK],
        effects: [{ targetStat: 'Nhanh nhẹn', modifier: '+10' }, { targetStat: 'Né Tránh', modifier: '+5%' }],
        rarity: 'Sử thi',
        price: 3500,
    },
    'Găng Tay Sát Thủ': {
        name: 'Găng Tay Sát Thủ',
        baseDescription: 'Đôi găng tay da mềm mại, cho phép ra đòn hiểm hóc và chính xác hơn.',
        category: 'Vật phẩm',
        slot: 'Găng Tay',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.LIGHT_ARMOR, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.FUNCTIONALITY.TACTICAL],
        effects: [{ targetStat: 'Tỷ lệ Chí mạng', modifier: '+10%' }, { targetStat: 'Sát thương Chí mạng', modifier: '+25%' }],
        rarity: 'Sử thi',
        price: 4000,
    },
    'Mũ Trùm Đầu Của Lãng Khách': {
        name: 'Mũ Trùm Đầu Của Lãng Khách',
        baseDescription: 'Một chiếc mũ trùm đầu bằng vải dày, giúp che giấu khuôn mặt và bảo vệ khỏi thời tiết.',
        category: 'Vật phẩm',
        slot: 'Mũ',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.LIGHT_ARMOR],
        effects: [{ targetStat: 'Phòng Thủ', modifier: '+5' }],
        rarity: 'Cao cấp',
        price: 60,
    },
    'Giày Da Bền Chắc': {
        name: 'Giày Da Bền Chắc',
        baseDescription: 'Một đôi giày da được gia cố, bảo vệ tốt và phù hợp cho những chuyến đi dài.',
        category: 'Vật phẩm',
        slot: 'Giày',
        tags: [ITEM_TAGS.EQUIPMENT_TYPE.LIGHT_ARMOR, ITEM_TAGS.MATERIAL_TYPE.LEATHER],
        effects: [{ targetStat: 'Phòng Thủ', modifier: '+8' }],
        rarity: 'Cao cấp',
        price: 80,
    },
    
    // --- PHỤ KIỆN NÂNG CAO & HIỆN ĐẠI ---
    'Kính Áp Tròng Thông Minh': {
        name: 'Kính Áp Tròng Thông Minh',
        baseDescription: 'Một cặp kính áp tròng công nghệ cao, hiển thị thông tin và phân tích dữ liệu trực tiếp lên võng mạc.',
        category: 'Vật phẩm',
        slot: 'Mặt',
        tags: [ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.FUNCTIONALITY.TACTICAL, ITEM_TAGS.MISC_TYPE.GLASSES],
        effects: [{ targetStat: 'Trí tuệ', modifier: '+10' }],
        rarity: 'Sử thi',
        price: 2000,
    },
    'Laptop Chuyên Dụng': {
        name: 'Laptop Chuyên Dụng',
        baseDescription: 'Một chiếc laptop được mã hóa và tùy chỉnh cho các hoạt động hacking và phân tích tình báo.',
        category: 'Vật phẩm',
        slot: 'Vật phẩm bỏ túi',
        tags: [ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.FUNCTIONALITY.TACTICAL],
        effects: [{ targetStat: 'Trí tuệ', modifier: '+15' }],
        rarity: 'Sử thi',
        price: 3000,
    },
    'Hoa Tai Bạc': {
        name: 'Hoa Tai Bạc',
        baseDescription: 'Một đôi hoa tai bạc đơn giản nhưng thanh lịch, làm tăng vẻ đẹp của người đeo.',
        category: 'Vật phẩm',
        slot: 'Hoa tai',
        tags: [ITEM_TAGS.MISC_TYPE.JEWELRY, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.ORIGIN.MARTIAL_ARTS, ITEM_TAGS.MATERIAL_TYPE.METAL],
        effects: [{ targetStat: 'Nhan sắc', modifier: '+5' }],
        rarity: 'Phổ thông',
        price: 30,
    },
    'Tai Nghe Trùm Đầu Chống Ồn': {
        name: 'Tai Nghe Trùm Đầu Chống Ồn',
        baseDescription: 'Một cặp tai nghe trùm đầu hiện đại, giúp người đeo tập trung bằng cách loại bỏ tiếng ồn xung quanh.',
        category: 'Vật phẩm',
        slot: 'Mũ',
        tags: [ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.MISC_TYPE.HEADPHONES_OVEREAR, ITEM_TAGS.FUNCTIONALITY.BUFF, ITEM_TAGS.FUNCTIONALITY.COSMETIC],
        rarity: 'Cao cấp',
        price: 150,
    },
    'Tai Nghe Nhét Tai': {
        name: 'Tai Nghe Nhét Tai',
        baseDescription: 'Một cặp tai nghe nhét tai nhỏ gọn, tiện lợi để nghe nhạc hoặc liên lạc.',
        category: 'Vật phẩm',
        slot: 'Mũ',
        tags: [ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.MISC_TYPE.HEADPHONES_INEAR, ITEM_TAGS.FUNCTIONALITY.COSMETIC],
        rarity: 'Phổ thông',
        price: 75,
    },
    'Mắt Kính Đen': {
        name: 'Mắt Kính Đen',
        baseDescription: 'Một cặp mắt kính râm màu đen, trông rất ngầu và giúp che giấu cảm xúc.',
        category: 'Vật phẩm',
        slot: 'Mặt',
        tags: [ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.MISC_TYPE.GLASSES, ITEM_TAGS.FUNCTIONALITY.COSMETIC],
        rarity: 'Phổ thông',
        price: 50,
    },
    'Đồng Hồ Đeo Tay Thép': {
        name: 'Đồng Hồ Đeo Tay Thép',
        baseDescription: 'Một chiếc đồng hồ đeo tay bằng thép không gỉ, thể hiện sự chính xác và đúng giờ.',
        category: 'Vật phẩm',
        slot: 'Cổ tay',
        tags: [ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.MISC_TYPE.WATCH, ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.FUNCTIONALITY.COSMETIC],
        rarity: 'Phổ thông',
        price: 120,
    },
    'Đồng Hồ Bỏ Túi Vàng': {
        name: 'Đồng Hồ Bỏ Túi Vàng',
        baseDescription: 'Một chiếc đồng hồ bỏ túi bằng vàng cổ điển, được chạm khắc tinh xảo, là biểu tượng của sự giàu có và địa vị.',
        category: 'Vật phẩm',
        slot: 'Vật phẩm bỏ túi',
        tags: [ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.MISC_TYPE.WATCH, ITEM_TAGS.FUNCTIONALITY.COSMETIC, ITEM_TAGS.MATERIAL_TYPE.METAL],
        rarity: 'Cao cấp',
        price: 300,
    },
    'Bật lửa Zippo': {
        name: 'Bật lửa Zippo',
        baseDescription: 'Một chiếc bật lửa kim loại cổ điển, bền bỉ và đáng tin cậy. Phát ra tiếng "cách" đặc trưng khi mở nắp.',
        category: 'Vật phẩm',
        slot: 'Vật phẩm bỏ túi',
        tags: [ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.MATERIAL_TYPE.METAL],
        rarity: 'Cao cấp',
        price: 100,
    },
    "Điện thoại thông minh 'Báo Đen'": {
        name: "Điện thoại thông minh 'Báo Đen'",
        baseDescription: "Một chiếc điện thoại được tùy chỉnh đặc biệt, tích hợp chip xử lý siêu tốc và các công cụ hacking cao cấp.",
        category: 'Vật phẩm',
        slot: 'Vật phẩm bỏ túi',
        tags: [ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.FUNCTIONALITY.TACTICAL],
        rarity: 'Sử thi',
        price: 2500,
    },
    'Nhẫn Bạc': {
        name: 'Nhẫn Bạc',
        baseDescription: 'Một chiếc nhẫn bạc được chế tác đơn giản, mang lại một chút may mắn cho người đeo.',
        category: 'Vật phẩm',
        slot: 'Nhẫn',
        tags: [ITEM_TAGS.MISC_TYPE.JEWELRY, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.ORIGIN.MARTIAL_ARTS, ITEM_TAGS.FUNCTIONALITY.BUFF, ITEM_TAGS.MATERIAL_TYPE.METAL],
        effects: [{ targetStat: 'May mắn', modifier: '+2' }],
        rarity: 'Phổ thông',
        price: 25,
    },
    'Vòng Cổ Bạc': {
        name: 'Vòng Cổ Bạc',
        baseDescription: 'Một sợi dây chuyền bạc mảnh mai với mặt dây chuyền nhỏ, tôn lên vẻ đẹp của người đeo.',
        category: 'Vật phẩm',
        slot: 'Phụ Kiện Cổ',
        tags: [ITEM_TAGS.MISC_TYPE.JEWELRY, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.ORIGIN.MARTIAL_ARTS, ITEM_TAGS.MATERIAL_TYPE.METAL],
        effects: [{ targetStat: 'Nhan sắc', modifier: '+7' }],
        rarity: 'Phổ thông',
        price: 40,
    },
    'Lắc Tay Bạc': {
        name: 'Lắc Tay Bạc',
        baseDescription: 'Một chiếc lắc tay bằng bạc, được chạm khắc hoa văn tinh xảo, giúp cử động của người đeo trở nên linh hoạt hơn.',
        category: 'Vật phẩm',
        slot: 'Cổ tay',
        tags: [ITEM_TAGS.MISC_TYPE.JEWELRY, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.ORIGIN.MARTIAL_ARTS, ITEM_TAGS.FUNCTIONALITY.BUFF, ITEM_TAGS.MATERIAL_TYPE.METAL],
        effects: [{ targetStat: 'Nhanh nhẹn', modifier: '+2' }],
        rarity: 'Phổ thông',
        price: 35,
    },

    // --- Y TẾ & SƠ CỨU HIỆN ĐẠI ---
    'Băng gạc': {
        name: 'Băng gạc',
        baseDescription: 'Một cuộn băng gạc sạch, dùng để băng bó vết thương hở và ngăn chảy máu.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.MEDICAL, ITEM_TAGS.ORIGIN.MODERN],
        effects: [], // Effect is narrative, e.g., stopping a "Chảy máu" status
        rarity: 'Phổ thông',
        price: 5,
    },
    'Băng Gạc Sơ Cứu': {
        name: 'Băng Gạc Sơ Cứu',
        baseDescription: 'Một miếng băng gạc đã được tẩm thuốc sát trùng, có thể dùng ngay để xử lý các vết thương nhỏ.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.MEDICAL, ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.FUNCTIONALITY.HEALING],
        effects: [{ targetStat: 'Sinh Lực', modifier: '+10' }],
        rarity: 'Phổ thông',
        price: 10,
    },
    'Thuốc sát trùng': {
        name: 'Thuốc sát trùng',
        baseDescription: 'Một lọ dung dịch dùng để làm sạch vết thương, ngăn ngừa nhiễm trùng.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.MEDICAL, ITEM_TAGS.ORIGIN.MODERN],
        effects: [],
        rarity: 'Phổ thông',
        price: 10,
    },
    'Thuốc giảm đau': {
        name: 'Thuốc giảm đau',
        baseDescription: 'Vài viên thuốc giúp giảm đau tạm thời, cho phép bạn phớt lờ các vết thương nhỏ và hồi phục thể lực.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.MEDICAL, ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.FUNCTIONALITY.BUFF],
        effects: [{ targetStat: 'Thể Lực', modifier: '+15' }],
        rarity: 'Phổ thông',
        price: 15,
    },
    'Hộp sơ cứu': {
        name: 'Hộp sơ cứu',
        baseDescription: 'Một hộp dụng cụ y tế đầy đủ bao gồm băng gạc, thuốc sát trùng, thuốc giảm đau và các vật dụng cần thiết khác. Hồi phục một lượng lớn sinh lực.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.MEDICAL, ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.FUNCTIONALITY.HEALING],
        effects: [{ targetStat: 'Sinh Lực', modifier: '+100' }],
        rarity: 'Cao cấp',
        price: 80,
    },

    // --- ĐAN DƯỢC & THUỐC (Võ Lâm / Tu Tiên / Fantasy) ---
    'Kim Sang Dược': {
        name: 'Kim Sang Dược',
        baseDescription: 'Loại thuốc trị ngoại thương nổi tiếng, có tác dụng cầm máu và làm liền vết thương nhanh chóng.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.HEALING, ITEM_TAGS.FUNCTIONALITY.COMBAT, ITEM_TAGS.ORIGIN.MARTIAL_ARTS],
        effects: [{ targetStat: 'Sinh Lực', modifier: '+30' }],
        rarity: 'Phổ thông',
        price: 20,
    },
    'Hồi Nguyên Đan': {
        name: 'Hồi Nguyên Đan',
        baseDescription: 'Một viên đan dược màu xanh nhạt, giúp tu sĩ/võ giả nhanh chóng hồi phục Linh Lực/Nội Lực đã tiêu hao.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.RESTORE, ITEM_TAGS.FUNCTIONALITY.COMBAT, ITEM_TAGS.ORIGIN.CULTIVATION, ITEM_TAGS.ORIGIN.MARTIAL_ARTS],
        effects: [{ targetStat: 'Linh Lực', modifier: '+50' }, { targetStat: 'Nội Lực', modifier: '+50' }],
        rarity: 'Phổ thông',
        price: 25,
    },
    'Hồi Linh Tán': {
        name: 'Hồi Linh Tán',
        baseDescription: 'Một loại thuốc bột đơn giản giúp tu sĩ Luyện Khí Kỳ phục hồi một lượng nhỏ linh lực.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.RESTORE, ITEM_TAGS.FUNCTIONALITY.COMBAT, ITEM_TAGS.ORIGIN.CULTIVATION],
        effects: [{ targetStat: 'Linh Lực', modifier: '+20' }],
        rarity: 'Phổ thông',
        price: 15,
    },
    'Sinh Mệnh Đan': {
        name: 'Sinh Mệnh Đan',
        baseDescription: 'Viên đan dược quý giá được luyện từ nhiều loại linh thảo, có khả năng cứu mạng trong gang tấc bằng cách bộc phát một lượng lớn sinh mệnh lực.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.HEAL_OVER_TIME, ITEM_TAGS.FUNCTIONALITY.COMBAT, ITEM_TAGS.ORIGIN.CULTIVATION],
        effects: [{ targetStat: 'Sinh Lực', modifier: '+200' }],
        rarity: 'Hiếm',
        price: 300,
    },
    'Giải Độc Đan': {
        name: 'Giải Độc Đan',
        baseDescription: 'Một viên đan dược phổ thông, có khả năng hóa giải các loại độc tố thông thường.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.DETOXIFY, ITEM_TAGS.ORIGIN.CULTIVATION],
        effects: [], // Narrative effect: removes "Trúng Độc" status
        rarity: 'Phổ thông',
        price: 30,
    },
    'Bách Thảo Giải Độc Hoàn': {
        name: 'Bách Thảo Giải Độc Hoàn',
        baseDescription: 'Được luyện từ tinh hoa của hàng trăm loại dược thảo, viên đan dược này có thể hóa giải hầu hết các loại kỳ độc trong thiên hạ.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.DETOXIFY, ITEM_TAGS.ORIGIN.MARTIAL_ARTS],
        effects: [],
        rarity: 'Hiếm',
        price: 400,
    },
    'Tăng Lực Đan': {
        name: 'Tăng Lực Đan',
        baseDescription: 'Một viên đan dược màu đỏ, có khả năng kích phát tiềm năng cơ bắp, giúp tăng Sức mạnh trong một khoảng thời gian ngắn.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.BUFF, ITEM_TAGS.FUNCTIONALITY.COMBAT, ITEM_TAGS.ORIGIN.CULTIVATION],
        effects: [{ targetStat: 'Sức mạnh', modifier: '+15' }],
        rarity: 'Cao cấp',
        price: 150,
    },
    'Tật Phong Đan': {
        name: 'Tật Phong Đan',
        baseDescription: 'Một viên đan dược màu xanh lục, giúp cơ thể trở nên nhẹ nhàng, tăng Nhanh nhẹn trong một khoảng thời gian ngắn.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.BUFF, ITEM_TAGS.FUNCTIONALITY.COMBAT, ITEM_TAGS.ORIGIN.CULTIVATION],
        effects: [{ targetStat: 'Nhanh nhẹn', modifier: '+15' }],
        rarity: 'Cao cấp',
        price: 150,
    },
    'Tẩy Tủy Đan': {
        name: 'Tẩy Tủy Đan',
        baseDescription: 'Một viên đan dược thần kỳ, có khả năng tẩy trừ tạp chất trong kinh mạch và xương tủy, cải thiện căn cốt và tư chất tu luyện một cách vĩnh viễn.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.IMPROVEMENT, ITEM_TAGS.ORIGIN.CULTIVATION, ITEM_TAGS.FUNCTIONALITY.UNIQUE],
        effects: [], // Narrative effect, handled by directives
        rarity: 'Sử thi',
        price: 10000,
    },
    'Trúc Cơ Đan': {
        name: 'Trúc Cơ Đan',
        baseDescription: 'Đan dược tối quan trọng cho tu sĩ Luyện Khí Kỳ đỉnh phong. Nó giúp ổn định linh khí, chống lại tâm ma và tăng đáng kể tỷ lệ thành công khi đột phá Trúc Cơ Kỳ.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.BREAKTHROUGH, ITEM_TAGS.ORIGIN.CULTIVATION],
        effects: [], // Narrative effect
        rarity: 'Hiếm',
        price: 2000,
    },
    'Ngưng Anh Đan': {
        name: 'Ngưng Anh Đan',
        baseDescription: 'Đan dược cực kỳ quý hiếm, giúp tu sĩ Kim Đan Kỳ đỉnh phong ngưng tụ Kim Đan thành Nguyên Anh. Nó bảo vệ thần hồn và tăng tỷ lệ thành công khi đối mặt với lôi kiếp đột phá.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.BREAKTHROUGH, ITEM_TAGS.ORIGIN.CULTIVATION],
        effects: [], // Narrative effect
        rarity: 'Sử thi',
        price: 25000,
    },

    // --- TIÊU HAO ---
    'Thuốc Hồi Phục Nhỏ': {
        name: 'Thuốc Hồi Phục Nhỏ',
        baseDescription: 'Một lọ thuốc màu đỏ nhạt, có vị ngọt. Hồi phục một lượng nhỏ sinh lực ngay lập tức khi uống.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.HEAL_OVER_TIME, ITEM_TAGS.FUNCTIONALITY.COMBAT, ITEM_TAGS.ORIGIN.FANTASY],
        effects: [{ targetStat: 'Sinh Lực', modifier: '+25' }],
        rarity: 'Phổ thông',
        price: 10,
    },
    'Hồi Khí Tán': {
        name: 'Hồi Khí Tán',
        baseDescription: 'Một loại thuốc bột giúp phục hồi một lượng nhỏ Nội Lực.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.RESTORE, ITEM_TAGS.FUNCTIONALITY.COMBAT, ITEM_TAGS.ORIGIN.MARTIAL_ARTS],
        effects: [{ targetStat: 'Nội Lực', modifier: '+20' }],
        rarity: 'Phổ thông',
        price: 15,
    },
    'Bom Khói': {
        name: 'Bom Khói',
        baseDescription: 'Một quả cầu gốm chứa đầy bột dễ cháy tạo ra một màn khói dày đặc khi vỡ, giúp che mắt kẻ địch và tạo cơ hội tẩu thoát.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.COMBAT, ITEM_TAGS.FUNCTIONALITY.TACTICAL, ITEM_TAGS.ORIGIN.MARTIAL_ARTS, ITEM_TAGS.FUNCTIONALITY.THROWABLE],
        effects: [],
        rarity: 'Phổ thông',
        price: 25,
    },
    'Lựu đạn M67': {
        name: 'Lựu đạn M67',
        baseDescription: 'Một quả lựu đạn phân mảnh, gây sát thương lớn trên một khu vực nhỏ sau vài giây.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.COMBAT, ITEM_TAGS.FUNCTIONALITY.THROWABLE, ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.FUNCTIONALITY.AOE],
        rarity: 'Hiếm',
        price: 100,
    },
    'Lương khô': {
        name: 'Lương khô',
        baseDescription: 'Một thanh thực phẩm khô, nén chặt, có giá trị dinh dưỡng cao nhưng vị không ngon. Giúp xua tan cơn đói và hồi phục một chút thể lực.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.MISC_TYPE.FOOD],
        effects: [{ targetStat: 'Thể Lực', modifier: '+10' }],
        rarity: 'Phổ thông',
        price: 5,
    },
    
    // --- NGUYÊN LIỆU CHUNG ---
    'Da Sói': {
        name: 'Da Sói',
        baseDescription: 'Tấm da của một con sói, có thể được dùng trong chế tác đồ da.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.LEATHER],
        price: 5,
        rarity: 'Phổ thông',
        source: ['Săn Sói ở các khu rừng hoặc đồng bằng.']
    },
    'Nanh Sói': {
        name: 'Nanh Sói',
        baseDescription: 'Chiếc nanh sắc nhọn của một con sói, có thể dùng làm vật liệu chế tác hoặc bùa hộ mệnh.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.BONE],
        price: 3,
        rarity: 'Phổ thông',
        source: ['Săn Sói.']
    },
    'Da Thú': {
        name: 'Da Thú',
        baseDescription: 'Một tấm da thú thông thường, dùng để chế tạo các loại giáp nhẹ hoặc túi đựng.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.LEATHER],
        price: 4,
        rarity: 'Phổ thông',
        source: ['Săn các loài động vật hoang dã như hươu, nai, heo rừng.']
    },
    'Xương Thú': {
        name: 'Xương Thú',
        baseDescription: 'Khúc xương của một loài động vật thông thường, có thể được nghiền thành bột hoặc làm vũ khí thô sơ.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.BONE],
        price: 2,
        rarity: 'Phổ thông',
        source: ['Săn hầu hết các loại động vật.']
    },

    // --- NGUYÊN LIỆU TỪ ĐỘNG VẬT ---
    'Vuốt Gấu': {
        name: 'Vuốt Gấu',
        baseDescription: 'Móng vuốt sắc và cứng của một con gấu, là nguyên liệu tốt để chế tạo vũ khí hoặc trang sức.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.BONE],
        price: 10,
        rarity: 'Phổ thông',
        source: ['Săn Gấu trong rừng sâu hoặc hang núi.']
    },
    'Da Hươu': {
        name: 'Da Hươu',
        baseDescription: 'Tấm da mềm mại của một con hươu, lý tưởng để chế tạo quần áo hoặc găng tay.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.LEATHER],
        price: 8,
        rarity: 'Phổ thông',
        source: ['Săn Hươu.']
    },
    'Lông Đại Bàng': {
        name: 'Lông Đại Bàng',
        baseDescription: 'Một chiếc lông vũ lớn từ đại bàng, thường được dùng để làm đuôi tên hoặc vật trang trí.',
        category: 'Nguyên liệu',
        tags: [CRAFTING_TAGS.ALCHEMY_FANTASY, ITEM_TAGS.ORIGIN.FANTASY],
        price: 7,
        rarity: 'Phổ thông',
        source: ['Tìm thấy ở các tổ đại bàng trên núi cao.']
    },
    'Nanh Heo Rừng': {
        name: 'Nanh Heo Rừng',
        baseDescription: 'Chiếc nanh dài và cong của một con heo rừng hung dữ, có thể được mài sắc để làm vũ khí.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.BONE],
        price: 9,
        rarity: 'Phổ thông',
        source: ['Săn Heo Rừng.']
    },
    'Vảy Rắn': {
        name: 'Vảy Rắn',
        baseDescription: 'Những chiếc vảy rắn lấp lánh, có thể dùng để trang trí áo giáp hoặc trong thuật giả kim.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.SCALE, CRAFTING_TAGS.ALCHEMY_FANTASY, ITEM_TAGS.ORIGIN.FANTASY],
        price: 5,
        rarity: 'Phổ thông',
        source: ['Săn các loài rắn.']
    },

    // --- NGUYÊN LIỆU TỪ QUÁI VẬT ---
    'Vảy Rồng': {
        name: 'Vảy Rồng',
        baseDescription: 'Một chiếc vảy cứng như kim cương từ một con rồng, có khả năng kháng lửa và ma thuật cực cao.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.SCALE, ITEM_TAGS.MATERIAL_TYPE.LEGENDARY, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.ORIGIN.CULTIVATION],
        price: 5000,
        rarity: 'Huyền thoại',
        source: ['Chiến lợi phẩm cực hiếm từ việc đánh bại Rồng.']
    },
    'Lông Griffin': {
        name: 'Lông Griffin',
        baseDescription: 'Một chiếc lông vũ từ sinh vật Griffin thần thoại, được cho là mang lại may mắn và có thể dùng để yểm bùa.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.ORIGIN.FANTASY],
        price: 1500,
        rarity: 'Sử thi',
        source: ['Săn Griffin ở các đỉnh núi cao.']
    },
    'Sừng Minotaur': {
        name: 'Sừng Minotaur',
        baseDescription: 'Chiếc sừng cứng và nặng của quái vật Minotaur, là nguyên liệu quý để chế tạo vũ khí và khiên.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.BONE, ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.ORIGIN.FANTASY],
        price: 400,
        rarity: 'Hiếm',
        source: ['Săn Minotaur trong các mê cung hoặc tàn tích cổ.']
    },
    'Lõi Slime': {
        name: 'Lõi Slime',
        baseDescription: 'Phần lõi sền sệt của một con Slime, là một chất xúc tác phổ biến trong thuật giả kim.',
        category: 'Nguyên liệu',
        tags: [CRAFTING_TAGS.ALCHEMY_FANTASY, ITEM_TAGS.ORIGIN.FANTASY],
        price: 10,
        rarity: 'Phổ thông',
        source: ['Săn Slime ở các khu vực ẩm ướt như hang động, đầm lầy.']
    },
    'Túi Độc Wyvern': {
        name: 'Túi Độc Wyvern',
        baseDescription: 'Túi chứa nọc độc chết người của một con Wyvern, dùng để tẩm vào vũ khí hoặc chế tạo độc dược.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.POISON_SAC, ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.ORIGIN.FANTASY],
        price: 550,
        rarity: 'Hiếm',
        source: ['Săn Wyvern.']
    },
    'Mắt Cyclops': {
        name: 'Mắt Cyclops',
        baseDescription: 'Nhãn cầu khổng lồ của một tên khổng lồ một mắt, chứa đựng sức mạnh ma thuật thô sơ.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.ORIGIN.FANTASY],
        rarity: 'Sử thi',
        price: 2000,
        source: ['Săn Cyclops.']
    },

    // --- THỰC PHẨM & THỊT ---
    'Thịt Nai Sống': {
        name: 'Thịt Nai Sống',
        baseDescription: 'Một miếng thịt nai tươi, cần được nấu chín trước khi ăn để tránh bệnh tật.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MISC_TYPE.FOOD, ITEM_TAGS.MATERIAL_TYPE.MEAT_RAW],
        price: 8,
        rarity: 'Phổ thông',
        source: ['Săn Nai.']
    },
    'Thịt Heo Rừng Sống': {
        name: 'Thịt Heo Rừng Sống',
        baseDescription: 'Thịt của heo rừng, khá dai nhưng bổ dưỡng. Nên được nấu chín kỹ.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MISC_TYPE.FOOD, ITEM_TAGS.MATERIAL_TYPE.MEAT_RAW],
        price: 7,
        rarity: 'Phổ thông',
        source: ['Săn Heo Rừng.']
    },
    'Thịt Quái Vật Sống': {
        name: 'Thịt Quái Vật Sống',
        baseDescription: 'Thịt từ một con quái vật không xác định. Có thể ăn được, nhưng cũng có thể chứa độc tố nhẹ hoặc gây ra các hiệu ứng phụ không mong muốn.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MISC_TYPE.FOOD, ITEM_TAGS.MATERIAL_TYPE.MEAT_RAW],
        price: 5,
        rarity: 'Phổ thông',
        source: ['Săn các loại quái vật cấp thấp.']
    },
    'Thịt Rồng Sống': {
        name: 'Thịt Rồng Sống',
        baseDescription: 'Một miếng thịt rồng quý hiếm, chứa đựng năng lượng dồi dào. Ăn sống rất nguy hiểm, nhưng nếu được chế biến đúng cách, nó có thể tăng cường sức mạnh vĩnh viễn.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MISC_TYPE.FOOD, ITEM_TAGS.MATERIAL_TYPE.MEAT_RAW, ITEM_TAGS.MATERIAL_TYPE.LEGENDARY],
        price: 8000,
        rarity: 'Huyền thoại',
        source: ['Chiến lợi phẩm cực hiếm từ Rồng.']
    },
    'Bít tết Quái vật (Nấu chín)': {
        name: 'Bít tết Quái vật (Nấu chín)',
        baseDescription: 'Một miếng bít tết được nấu chín kỹ từ thịt quái vật, giúp hồi phục một lượng lớn sinh lực.',
        category: 'Vật phẩm',
        slot: 'Không có',
        tags: [ITEM_TAGS.FUNCTIONALITY.CONSUMABLE, ITEM_TAGS.FUNCTIONALITY.HEAL_OVER_TIME, ITEM_TAGS.MISC_TYPE.FOOD],
        effects: [{ targetStat: 'Sinh Lực', modifier: '+50' }],
        rarity: 'Hiếm',
        price: 30,
    },

    // --- NGUYÊN LIỆU TU TIÊN ---
    'Linh Thảo': {
        name: 'Linh Thảo',
        baseDescription: 'Loại cỏ dại chứa đựng linh khí loãng, là nguyên liệu cơ bản nhất trong luyện đan.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.HERB, ITEM_TAGS.ORIGIN.CULTIVATION],
        price: 5,
        rarity: 'Phổ thông',
        source: ['Hái lượm ở những nơi có linh khí.']
    },
    'Huyết Tinh Thảo': {
        name: 'Huyết Tinh Thảo',
        baseDescription: 'Loại cỏ có màu đỏ như máu, chứa đựng khí huyết dồi dào, dùng để luyện các loại đan dược bổ máu.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.HERB, ITEM_TAGS.ORIGIN.CULTIVATION],
        price: 8,
        rarity: 'Phổ thông',
        source: ['Tìm thấy ở các chiến trường cổ hoặc nơi có âm khí.']
    },
    'Đoạn Hồn Thảo': {
        name: 'Đoạn Hồn Thảo',
        baseDescription: 'Loại cỏ độc màu tím sẫm, có khả năng làm tổn thương thần hồn, là nguyên liệu chính cho các loại độc dược và nguyền rủa.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.HERB, ITEM_TAGS.ORIGIN.CULTIVATION, ELEMENTAL_TAGS.EXTENDED_ELEMENTS.POISON],
        price: 150,
        rarity: 'Cao cấp',
        source: ['Mọc ở những vùng đất bị nguyền rủa hoặc có độc khí.']
    },
    'Dưỡng Hồn Mộc': {
        name: 'Dưỡng Hồn Mộc',
        baseDescription: 'Một đoạn gỗ tâm của cây cổ thụ ngàn năm, tỏa ra khí tức ấm áp giúp nuôi dưỡng và củng cố thần hồn.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.WOOD, ITEM_TAGS.ORIGIN.CULTIVATION],
        price: 200,
        rarity: 'Cao cấp',
        source: ['Khai thác từ các cây cổ thụ có linh tính.']
    },
    'Thiên Niên Chu Quả': {
        name: 'Thiên Niên Chu Quả',
        baseDescription: 'Loại quả màu đỏ son, mọc nghìn năm mới kết trái. Chứa đựng sinh mệnh lực khổng lồ, có thể kéo dài tuổi thọ hoặc tăng mạnh tu vi.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.SPIRIT_FRUIT, ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.ORIGIN.CULTIVATION],
        rarity: 'Sử thi',
        price: 20000,
        source: ['Phần thưởng hiếm từ các bí cảnh cổ xưa.']
    },
    'Yêu Đan (Nhất Giai)': {
        name: 'Yêu Đan (Nhất Giai)',
        baseDescription: 'Nội đan kết tinh từ yêu thú cấp thấp, chứa đựng yêu lực thuần túy.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.ORIGIN.CULTIVATION],
        price: 20,
        rarity: 'Phổ thông',
        source: ['Săn các yêu thú cấp 1.']
    },
    'Bích Nhãn Thiềm Thừ Độc Nang': {
        name: 'Bích Nhãn Thiềm Thừ Độc Nang',
        baseDescription: 'Túi độc của một con cóc yêu có đôi mắt ngọc bích. Nọc độc cực mạnh, có thể ăn mòn cả pháp khí.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.POISON_SAC, ITEM_TAGS.ORIGIN.CULTIVATION, ELEMENTAL_TAGS.EXTENDED_ELEMENTS.POISON],
        price: 300,
        rarity: 'Hiếm',
        source: ['Săn Bích Nhãn Thiềm Thừ.']
    },
    'Cốt Long Chi Dực': {
        name: 'Cốt Long Chi Dực',
        baseDescription: 'Cánh xương của một con rồng xương đã chết, vẫn còn sót lại ma khí và cực kỳ cứng rắn, là vật liệu tuyệt hảo để luyện chế phi hành pháp bảo hoặc ma khí.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.BONE, ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.ORIGIN.CULTIVATION, ELEMENTAL_TAGS.MAGIC_TYPE.DEMONIC],
        rarity: 'Sử thi',
        price: 5000,
        source: ['Loot từ Cốt Long.']
    },
    'Linh Thạch Hạ Phẩm': {
        name: 'Linh Thạch Hạ Phẩm',
        baseDescription: 'Loại đá chứa linh khí cấp thấp, vừa là tiền tệ, vừa là tài nguyên để tu luyện và bố trí trận pháp.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.CURRENCY, ITEM_TAGS.ORIGIN.CULTIVATION, ITEM_TAGS.MATERIAL_TYPE.GEMSTONE],
        price: 1,
        rarity: 'Phổ thông',
        source: ['Khai thác từ linh mạch hoặc rơi ra từ yêu thú.']
    },
    'Huyền Thiết': {
        name: 'Huyền Thiết',
        baseDescription: 'Một loại khoáng thạch màu đen, cứng rắn và ẩn chứa linh khí, là vật liệu phổ biến để luyện chế pháp khí.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.ORE, ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.ORIGIN.CULTIVATION],
        price: 15,
        rarity: 'Phổ thông',
        source: ['Khai thác từ các mỏ khoáng.']
    },
    'Tử Lôi Tinh Thạch': {
        name: 'Tử Lôi Tinh Thạch',
        baseDescription: 'Một viên tinh thạch màu tím, ẩn chứa sức mạnh của sấm sét cuồng bạo. Vật liệu tuyệt vời để luyện chế pháp bảo thuộc tính Lôi.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.ORE, ELEMENTAL_TAGS.EXTENDED_ELEMENTS.LIGHTNING, ITEM_TAGS.ORIGIN.CULTIVATION, ITEM_TAGS.MATERIAL_TYPE.CRYSTAL],
        price: 400,
        rarity: 'Hiếm',
        source: ['Tìm thấy ở những nơi bị sét đánh thường xuyên.']
    },
    'Lưu Ly Huyễn Tinh': {
        name: 'Lưu Ly Huyễn Tinh',
        baseDescription: 'Một viên pha lê trong suốt như lưu ly, có khả năng bẻ cong ánh sáng và tạo ra ảo ảnh. Vật liệu cốt lõi cho các trận pháp và pháp bảo gây ảo giác.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.ORE, ITEM_TAGS.MATERIAL_TYPE.CRYSTAL, ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.ORIGIN.CULTIVATION],
        price: 3500,
        rarity: 'Sử thi',
        source: ['Hiếm có trong các bí cảnh cổ xưa.']
    },
    'Hàn Thiết': {
        name: 'Hàn Thiết',
        baseDescription: 'Một loại sắt hiếm, mang tính hàn, dùng để rèn các pháp bảo thuộc tính Băng hoặc khắc chế yêu ma Hỏa thuộc tính.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.ORE, ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.ORIGIN.CULTIVATION, ELEMENTAL_TAGS.EXTENDED_ELEMENTS.ICE],
        price: 250,
        rarity: 'Hiếm',
        source: ['Khai thác từ các mỏ sắt ở vùng đất băng giá.']
    },
    'Tử Đồng': {
        name: 'Tử Đồng',
        baseDescription: 'Đồng có màu tím, dẻo dai và dẫn linh lực tốt, thích hợp làm lõi cho các trận pháp hoặc pháp khí phức tạp.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.ORE, ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.ORIGIN.CULTIVATION],
        price: 180,
        rarity: 'Cao cấp',
        source: ['Khai thác từ các mỏ đồng đặc biệt.']
    },
    'Tinh Kim': {
        name: 'Tinh Kim',
        baseDescription: 'Kim loại quý hiếm được hình thành ở nơi có linh khí cực kỳ tinh khiết hoặc rơi xuống từ các vì sao, nhẹ hơn thép nhưng cứng hơn gấp bội, có khả năng dẫn truyền ma thuật tuyệt vời. Là vật liệu thượng hạng để luyện chế Linh Khí và chế tạo thần binh.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.ORE, ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.ORIGIN.CULTIVATION, ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.MATERIAL_TYPE.LEGENDARY, ITEM_TAGS.ORIGIN.FANTASY],
        price: 30000,
        rarity: 'Huyền thoại',
        source: ['Tìm thấy trong lõi của các linh mạch cực phẩm.', 'Khai thác từ các mỏ thiên thạch.']
    },

    // --- NGUYÊN LIỆU VÕ LÂM ---
    'Sắt Thô': {
        name: 'Sắt Thô',
        baseDescription: 'Quặng sắt chưa được tinh luyện, là vật liệu cơ bản để rèn đúc vũ khí và áo giáp.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.ORE, ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.ORIGIN.MARTIAL_ARTS],
        price: 5,
        rarity: 'Phổ thông',
        source: ['Khai thác từ các mỏ sắt.']
    },
    'Vải Thô': {
        name: 'Vải Thô',
        baseDescription: 'Loại vải thông thường, dùng để may quần áo hoặc làm băng gạc.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.FABRIC, ITEM_TAGS.ORIGIN.MARTIAL_ARTS],
        price: 2,
        rarity: 'Phổ thông',
        source: ['Mua từ các tiệm may hoặc nông dân.']
    },
    'Dược Thảo': {
        name: 'Dược Thảo',
        baseDescription: 'Các loại thảo dược thông thường mọc trên núi, dùng để bào chế các loại thuốc trị thương cơ bản.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.HERB, ITEM_TAGS.ORIGIN.MARTIAL_ARTS],
        price: 4,
        rarity: 'Phổ thông',
        source: ['Hái lượm trong rừng hoặc trên núi.']
    },
    'Bách Thảo Lộ': {
        name: 'Bách Thảo Lộ',
        baseDescription: 'Tinh chất được cô đọng từ hàng trăm loại thảo dược quý hiếm, có khả năng giải trừ nhiều loại độc tố và chữa trị nội thương.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.ORIGIN.MARTIAL_ARTS, ITEM_TAGS.MATERIAL_TYPE.HERB],
        price: 250,
        rarity: 'Hiếm',
        source: ['Bào chế từ nhiều loại dược thảo quý.']
    },
    'Cửu Diệp Chi': {
        name: 'Cửu Diệp Chi',
        baseDescription: 'Một loại nấm linh chi huyền thoại có chín lá, được cho là có khả năng cải tử hoàn sinh.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.HERB, ITEM_TAGS.MATERIAL_TYPE.LEGENDARY, ITEM_TAGS.ORIGIN.MARTIAL_ARTS],
        price: 18000,
        rarity: 'Huyền thoại',
        source: ['Cực hiếm, chỉ mọc ở những nơi có địa thế đặc biệt.']
    },
    'Thiên Tàm Ti': {
        name: 'Thiên Tàm Ti',
        baseDescription: 'Tơ của một loài tằm trời, mỏng manh nhưng bền chắc lạ thường, đao thương bất nhập. Dùng để chế tạo nhuyễn giáp hoặc vũ khí mềm như roi.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.MATERIAL_TYPE.FABRIC, ITEM_TAGS.ORIGIN.MARTIAL_ARTS],
        rarity: 'Sử thi',
        price: 4500,
        source: ['Thu thập từ Thiên Tằm.']
    },
    'Vẫn Thạch': {
        name: 'Vẫn Thạch',
        baseDescription: 'Một khối sắt từ thiên thạch rơi xuống, chứa các kim loại hiếm không có trên mặt đất, cực kỳ cứng rắn và sắc bén sau khi rèn.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.ORE, ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.ORIGIN.MARTIAL_ARTS, ITEM_TAGS.MATERIAL_TYPE.METAL],
        rarity: 'Sử thi',
        price: 6000,
        source: ['Tìm kiếm ở những nơi thiên thạch rơi.']
    },
    'Thép Tinh Luyện': {
        name: 'Thép Tinh Luyện',
        baseDescription: 'Thép đã được tôi luyện trăm lần, loại bỏ tạp chất, cực kỳ cứng và sắc bén, là vật liệu để đúc nên các thần binh lợi khí.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.ORIGIN.MARTIAL_ARTS],
        price: 100,
        rarity: 'Cao cấp',
        source: ['Rèn từ Sắt Thô bởi các thợ rèn bậc thầy.']
    },
    'Ô Kim': {
        name: 'Ô Kim',
        baseDescription: 'Một loại sắt đen bóng, nặng và cứng dị thường, có khả năng hấp thụ nội lực. Dùng để rèn các loại vũ khí nặng như trọng kiếm hoặc búa.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.ORE, ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.ORIGIN.MARTIAL_ARTS],
        price: 300,
        rarity: 'Hiếm',
        source: ['Khai thác từ các mỏ sâu trong lòng đất.']
    },

    // --- NGUYÊN LIỆU DỊ GIỚI FANTASY ---
    'Ma Thạch Vụn': {
        name: 'Ma Thạch Vụn',
        baseDescription: 'Mảnh vỡ của một viên ma thạch lớn hơn, chứa đựng một lượng nhỏ ma lực.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.ORE, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.MATERIAL_TYPE.CRYSTAL],
        price: 8,
        rarity: 'Phổ thông',
        source: ['Rơi ra từ các quái vật hệ ma thuật.']
    },
    'Gỗ Sồi': {
        name: 'Gỗ Sồi',
        baseDescription: 'Gỗ từ cây sồi, chắc chắn và bền bỉ, dùng để chế tạo cán vũ khí, khiên hoặc đồ nội thất.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.WOOD, ITEM_TAGS.ORIGIN.FANTASY],
        price: 3,
        rarity: 'Phổ thông',
        source: ['Chặt cây Sồi trong rừng.']
    },
    'Da Yêu Tinh': {
        name: 'Da Yêu Tinh',
        baseDescription: 'Da của một con Goblin, mỏng nhưng dẻo dai, có thể dùng để chế tạo giáp da cấp thấp.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.LEATHER, ITEM_TAGS.ORIGIN.FANTASY],
        price: 6,
        rarity: 'Phổ thông',
        source: ['Săn Goblin.']
    },
    'Nấm Huỳnh Quang': {
        name: 'Nấm Huỳnh Quang',
        baseDescription: 'Loại nấm phát ra ánh sáng xanh lam mờ ảo trong bóng tối, là một thành phần phổ biến trong thuật giả kim.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.HERB, ITEM_TAGS.ORIGIN.FANTASY],
        price: 7,
        rarity: 'Phổ thông',
        source: ['Hái lượm trong các hang động tối.']
    },
    'Nguyệt Ảnh Hoa': {
        name: 'Nguyệt Ảnh Hoa',
        baseDescription: 'Bông hoa chỉ nở dưới ánh trăng, cánh hoa của nó có khả năng khúc xạ ánh sáng. Nguyên liệu chính cho các loại thuốc tàng hình.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.HERB, ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.ORIGIN.FANTASY],
        price: 180,
        rarity: 'Hiếm',
        source: ['Hái lượm vào ban đêm khi trăng tròn.']
    },
    'Nước Mắt Griffin': {
        name: 'Nước Mắt Griffin',
        baseDescription: 'Một giọt nước mắt từ sinh vật Griffin cao quý, có đặc tính thanh tẩy và chữa lành mạnh mẽ.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.ORIGIN.FANTASY],
        rarity: 'Sử thi',
        price: 4000,
        source: ['Phần thưởng hiếm từ Griffin.']
    },
    'Tim Rồng': {
        name: 'Tim Rồng',
        baseDescription: 'Trái tim của một con rồng, vẫn còn đập nhẹ và tỏa ra nhiệt lượng. Nguồn năng lượng ma thuật khổng lồ, là nguyên liệu tối thượng cho việc yểm bùa vũ khí và áo giáp.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.LEGENDARY, ITEM_TAGS.ORIGIN.FANTASY],
        price: 50000,
        rarity: 'Huyền thoại',
        source: ['Chiến lợi phẩm từ Rồng.']
    },
    // Đã gộp object 'Tinh Kim' phía trên
    'Đá Hồn': {
        name: 'Đá Hồn',
        baseDescription: 'Một viên đá quý có khả năng chứa đựng linh hồn của sinh vật sống. Được các nhà chiêu hồn và yểm bùa sư săn lùng.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.SOUL_STONE, ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.MATERIAL_TYPE.GEMSTONE],
        rarity: 'Sử thi',
        price: 7000,
        source: ['Rơi ra từ các sinh vật có linh hồn mạnh mẽ.']
    },
    'Bạc': {
        name: 'Bạc',
        baseDescription: 'Kim loại quý có màu trắng sáng. Vũ khí bạc có hiệu quả đặc biệt chống lại một số loại quái vật như ma sói và vong linh.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.ORE, ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.ORIGIN.FANTASY, ITEM_TAGS.FUNCTIONALITY.BLESSED],
        price: 50,
        rarity: 'Cao cấp',
        source: ['Khai thác từ các mỏ bạc.']
    },
    'Vàng': {
        name: 'Vàng',
        baseDescription: 'Kim loại quý màu vàng, mềm hơn sắt nhưng có khả năng dẫn truyền ma thuật tốt, thường được dùng để yểm bùa hoặc chế tác trang sức ma thuật.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.ORE, ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.ORIGIN.FANTASY],
        price: 100,
        rarity: 'Cao cấp',
        source: ['Khai thác từ các mỏ vàng.']
    },
    'Thép': {
        name: 'Thép',
        baseDescription: 'Hợp kim của sắt và carbon, cứng và bền hơn sắt, là vật liệu phổ biến nhất cho vũ khí và áo giáp thông thường.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.ORIGIN.FANTASY],
        price: 10,
        rarity: 'Phổ thông',
        source: ['Được rèn từ sắt bởi các thợ rèn.']
    },

    // --- NGUYÊN LIỆU HẬU TẬN THẾ ---
    'Sắt Vụn': {
        name: 'Sắt Vụn',
        baseDescription: 'Những mảnh kim loại rỉ sét thu lượm từ các công trình đổ nát, cực kỳ hữu ích cho việc chế tạo và sửa chữa.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.ORIGIN.MODERN],
        price: 3,
        rarity: 'Phổ thông',
        source: ['Thu lượm ở các tàn tích đô thị.']
    },
    'Vải Rách': {
        name: 'Vải Rách',
        baseDescription: 'Những mảnh vải bẩn và rách, có thể được dùng để làm băng gạc hoặc vá quần áo.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.FABRIC, ITEM_TAGS.ORIGIN.MODERN],
        price: 1,
        rarity: 'Phổ thông',
        source: ['Thu lượm ở các khu dân cư bỏ hoang.']
    },
    'Linh Kiện Điện Tử': {
        name: 'Linh Kiện Điện Tử',
        baseDescription: 'Các vi mạch, dây dẫn và bảng mạch được gỡ ra từ các thiết bị điện tử hỏng, cần thiết để sửa chữa hoặc chế tạo công cụ phức tạp.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.ORIGIN.MODERN],
        price: 15,
        rarity: 'Phổ thông',
        source: ['Tháo dỡ từ các thiết bị điện tử cũ.']
    },
    'Nhựa': {
        name: 'Nhựa',
        baseDescription: 'Những mảnh nhựa vỡ từ các vật dụng hàng ngày, là một vật liệu chế tạo đa dụng.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.ORIGIN.MODERN],
        price: 2,
        rarity: 'Phổ thông',
        source: ['Thu lượm ở khắp mọi nơi.']
    },
    'Băng Gạc Bẩn': {
        name: 'Băng Gạc Bẩn',
        baseDescription: 'Băng gạc đã qua sử dụng, cần được khử trùng trước khi dùng để tránh nhiễm trùng.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.FUNCTIONALITY.MEDICAL, ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.MATERIAL_TYPE.FABRIC],
        price: 1,
        rarity: 'Phổ thông',
        source: ['Tìm thấy trong các hộp cứu thương cũ.']
    },
    'Phụ tùng Ô tô': {
        name: 'Phụ tùng Ô tô',
        baseDescription: 'Các bộ phận còn sử dụng được từ những chiếc xe hơi bị bỏ hoang, dùng để sửa chữa hoặc chế tạo phương tiện di chuyển.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.MATERIAL_TYPE.METAL],
        price: 50,
        rarity: 'Phổ thông',
        source: ['Tháo dỡ từ xe hơi bỏ hoang.']
    },
    'Thuốc Súng': {
        name: 'Thuốc Súng',
        baseDescription: 'Một loại bột màu đen dễ cháy, là thành phần cốt lõi để chế tạo đạn dược hoặc thuốc nổ.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.ORIGIN.MODERN],
        price: 40,
        rarity: 'Phổ thông',
        source: ['Chế tạo từ các hóa chất hoặc tìm thấy trong đạn cũ.']
    },
    'Hạt Giống': {
        name: 'Hạt Giống',
        baseDescription: 'Những hạt giống quý giá được bảo quản cẩn thận, là hy vọng để xây dựng lại một nguồn cung cấp thực phẩm bền vững.',
        category: 'Nguyên liệu',
        tags: [CRAFTING_TAGS.FARMING],
        price: 200,
        rarity: 'Cao cấp',
        source: ['Tìm thấy ở các trung tâm nông nghiệp hoặc cửa hàng cũ.']
    },
    'Nhôm': {
        name: 'Nhôm',
        baseDescription: 'Kim loại nhẹ, chống gỉ, được dùng trong nhiều ứng dụng hiện đại. Có thể thu lượm từ các bộ phận máy bay hoặc đồ gia dụng.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.ORIGIN.MODERN],
        price: 8,
        rarity: 'Phổ thông',
        source: ['Thu lượm từ các tàn tích công nghệ cao.']
    },
    'Titan': {
        name: 'Titan',
        baseDescription: 'Một kim loại cực kỳ bền và nhẹ, được sử dụng trong các công nghệ cao cấp và cấy ghép y tế. Rất khó để gia công.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.ORIGIN.MODERN, ITEM_TAGS.MATERIAL_TYPE.RARE],
        price: 800,
        rarity: 'Hiếm',
        source: ['Tìm thấy trong các phòng thí nghiệm hoặc căn cứ quân sự bỏ hoang.']
    },

    // --- NGUYÊN LIỆU CAO CẤP & ĐẶC BIỆT ---
    'Adamantium': {
        name: 'Adamantium',
        baseDescription: 'Một kim loại huyền thoại, gần như không thể phá hủy, được các thợ rèn vĩ đại nhất săn lùng để đúc nên vũ khí và áo giáp với chất lượng vô song.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.MATERIAL_TYPE.LEGENDARY, ITEM_TAGS.MATERIAL_TYPE.ORE],
        price: 10000,
        rarity: 'Huyền thoại',
        source: ['Cực hiếm, chỉ có trong các mỏ sâu nhất hoặc từ lõi thiên thạch.']
    },
    'Sợi Carbon': {
        name: 'Sợi Carbon',
        baseDescription: 'Một vật liệu cực kỳ bền chắc nhưng rất nhẹ, được sử dụng để chế tạo các loại giáp và linh kiện hiện đại, tiên tiến.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.ORIGIN.MODERN],
        price: 500,
        rarity: 'Hiếm',
        source: ['Tìm thấy trong các phòng thí nghiệm công nghệ cao hoặc căn cứ quân sự.']
    },
    'Hợp Kim Siêu Cứng': {
        name: 'Hợp Kim Siêu Cứng',
        baseDescription: 'Một loại hợp kim được đúc từ nhiều kim loại hiếm, mang lại sự cân bằng giữa độ cứng và độ dẻo. Một vật liệu đa dụng cho các trang bị từ trung đến cao cấp.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.METAL, ITEM_TAGS.MATERIAL_TYPE.RARE, ITEM_TAGS.MATERIAL_TYPE.ORE],
        price: 750,
        rarity: 'Hiếm',
        source: ['Chế tạo bởi các thợ rèn bậc thầy.']
    },
    'Vỏ Cây Thế Giới': {
        name: 'Vỏ Cây Thế Giới',
        baseDescription: 'Một mảnh vỏ cây từ Cây Thế Giới trong thần thoại, thấm đẫm sinh mệnh lực của chính hành tinh. Một nguyên liệu cực kỳ mạnh mẽ trong giả kim và chế tác thần khí.',
        category: 'Nguyên liệu',
        tags: [ITEM_TAGS.MATERIAL_TYPE.WOOD, ITEM_TAGS.MATERIAL_TYPE.LEGENDARY, ITEM_TAGS.ORIGIN.FANTASY],
        price: 15000,
        rarity: 'Huyền thoại',
        source: ['Phần thưởng từ nhiệm vụ cấp độ thế giới.']
    },

    // --- RECIPES (using the new materials) ---
    'Sơ Đồ Chế Tạo: Hồi Khí Tán': {
        name: 'Sơ Đồ Chế Tạo: Hồi Khí Tán',
        baseDescription: 'Công thức bào chế Hồi Khí Tán, một loại thuốc đơn giản giúp võ giả phục hồi một chút nội lực.',
        category: 'Sơ Đồ Chế Tạo',
        tags: [CRAFTING_TAGS.PHARMACY, ITEM_TAGS.ORIGIN.MARTIAL_ARTS],
        recipeData: {
            ingredients: [
                { name: 'Dược Thảo', quantity: 3 },
            ],
            product: 'Hồi Khí Tán',
            difficulty: 1,
            craftingSkill: 'Chế Dược Sơ Cấp',
        },
        rarity: 'Phổ thông',
        price: 20,
    },
    'Sơ Đồ Chế Tạo: Hồi Linh Tán': {
        name: 'Sơ Đồ Chế Tạo: Hồi Linh Tán',
        baseDescription: 'Công thức luyện chế Hồi Linh Tán, một loại thuốc đơn giản giúp tu sĩ phục hồi một chút linh lực.',
        category: 'Sơ Đồ Chế Tạo',
        tags: [CRAFTING_TAGS.ALCHEMY_CULTIVATION, ITEM_TAGS.ORIGIN.CULTIVATION],
        recipeData: {
            ingredients: [ { name: 'Linh Thảo', quantity: 3 } ],
            product: 'Hồi Linh Tán',
            difficulty: 1,
            craftingSkill: 'Luyện Đan Sơ Cấp',
        },
        rarity: 'Phổ thông',
        price: 20,
    },
    'Sơ Đồ Chế Tạo: Kiếm Sắt': {
        name: 'Sơ Đồ Chế Tạo: Kiếm Sắt',
        baseDescription: 'Công thức rèn một thanh Kiếm Sắt cơ bản.',
        category: 'Sơ Đồ Chế Tạo',
        tags: [CRAFTING_TAGS.FORGING],
        recipeData: {
            ingredients: [ { name: 'Sắt Thô', quantity: 5 }, { name: 'Gỗ Sồi', quantity: 1 } ],
            product: 'Kiếm Sắt',
            difficulty: 2,
            craftingSkill: 'Rèn Đúc Cơ Bản',
        },
        rarity: 'Phổ thông',
        price: 20,
    },
    'Sơ Đồ Chế Tạo: Thuốc Hồi Phục Nhỏ': {
        name: 'Sơ Đồ Chế Tạo: Thuốc Hồi Phục Nhỏ',
        baseDescription: 'Công thức giả kim để tạo ra một lọ thuốc hồi phục sinh lực nhỏ.',
        category: 'Sơ Đồ Chế Tạo',
        tags: [CRAFTING_TAGS.ALCHEMY_FANTASY],
        recipeData: {
            ingredients: [ { name: 'Lõi Slime', quantity: 2 }, { name: 'Nấm Huỳnh Quang', quantity: 1 } ],
            product: 'Thuốc Hồi Phục Nhỏ',
            difficulty: 1,
            craftingSkill: 'Giả Kim Sơ Cấp',
        },
        rarity: 'Phổ thông',
        price: 20,
    },
    'Sơ Đồ Chế Tạo: Balo Da Thú': {
        name: 'Sơ Đồ Chế Tạo: Balo Da Thú',
        baseDescription: 'Công thức chế tác một chiếc balo đơn giản từ da thú, giúp tăng sức chứa.',
        category: 'Sơ Đồ Chế Tạo',
        tags: [CRAFTING_TAGS.ARTISAN],
        recipeData: {
            ingredients: [ { name: 'Da Thú', quantity: 5 } ],
            product: 'Balo Da Thú',
            difficulty: 2,
            craftingSkill: 'Chế Tác Da Sơ Cấp',
        },
        rarity: 'Phổ thông',
        price: 20,
    },
    'Sơ Đồ Chế Tạo: Dao Găm Chiến Thuật': {
        name: 'Sơ Đồ Chế Tạo: Dao Găm Chiến Thuật',
        baseDescription: 'Công thức chế tạo một con dao găm đơn giản từ sắt vụn.',
        category: 'Sơ Đồ Chế Tạo',
        tags: [CRAFTING_TAGS.MANUFACTURING],
        recipeData: {
            ingredients: [ { name: 'Sắt Vụn', quantity: 10 } ],
            product: 'Dao Găm Chiến Thuật',
            difficulty: 1,
            craftingSkill: 'Chế Tạo Cơ Bản',
        },
        rarity: 'Phổ thông',
        price: 20,
    },
    'Công thức: Bít tết Quái vật': {
        name: 'Công thức: Bít tết Quái vật',
        baseDescription: 'Công thức nấu một miếng bít tết đơn giản từ thịt quái vật.',
        category: 'Sơ Đồ Chế Tạo',
        tags: [CRAFTING_TAGS.COOKING],
        recipeData: {
            ingredients: [ { name: 'Thịt Quái Vật Sống', quantity: 1 } ],
            product: 'Bít tết Quái vật (Nấu chín)',
            difficulty: 1,
            craftingSkill: 'Nấu Ăn Sơ Cấp',
        },
        rarity: 'Phổ thông',
        price: 10,
    },
    'Sơ Đồ Chế Tạo: Băng Gạc Sơ Cứu': {
        name: 'Sơ Đồ Chế Tạo: Băng Gạc Sơ Cứu',
        baseDescription: 'Công thức chế tạo băng gạc y tế đơn giản từ vải sạch.',
        category: 'Sơ Đồ Chế Tạo',
        tags: [CRAFTING_TAGS.MANUFACTURING, ITEM_TAGS.FUNCTIONALITY.MEDICAL],
        recipeData: {
            ingredients: [ { name: 'Vải Rách', quantity: 2 } ],
            product: 'Băng Gạc Sơ Cứu',
            difficulty: 1,
            craftingSkill: 'Sơ Cứu Cơ Bản',
        },
        rarity: 'Phổ thông',
        price: 15,
    },
};

export const DEFAULT_GENRE_RECIPES: Record<string, string[]> = {
    'Tu Tiên': ['Sơ Đồ Chế Tạo: Hồi Linh Tán'],
    'Huyền Huyễn Truyền Thuyết': ['Sơ Đồ Chế Tạo: Hồi Linh Tán'],
    'Võ Lâm': ['Sơ Đồ Chế Tạo: Hồi Khí Tán'],
    'Thời Chiến (Trung Hoa/Nhật Bản)': ['Sơ Đồ Chế Tạo: Hồi Khí Tán'],
    'Dị Giới Fantasy': ['Sơ Đồ Chế Tạo: Thuốc Hồi Phục Nhỏ'],
    'Thế Giới Giả Tưởng (Game/Tiểu Thuyết)': ['Sơ Đồ Chế Tạo: Thuốc Hồi Phục Nhỏ'],
    'Hậu Tận Thế': ['Sơ Đồ Chế Tạo: Dao Găm Chiến Thuật'],
    'Đô Thị Hiện Đại': ['Sơ Đồ Chế Tạo: Băng Gạc Sơ Cứu'],
    'Đô Thị Hiện Đại 100% bình thường': ['Sơ Đồ Chế Tạo: Băng Gạc Sơ Cứu'],
    'Đô Thị Dị Biến': ['Sơ Đồ Chế Tạo: Băng Gạc Sơ Cứu'],
    'Default': ['Sơ Đồ Chế Tạo: Thuốc Hồi Phục Nhỏ'],
};
