/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

// This file assembles various lore libraries from sub-modules into a single,
// comprehensive world-building resource for the AI.

import { LORE_LIBRARY_ATTIRE, LORE_LIBRARY_HUMAN_DESCRIPTION, LORE_LIBRARY_HAIR, LORE_LIBRARY_AGING_APPEARANCE } from './appearance';
import { LORE_LIBRARY_ASTRONOMICAL_PHENOMENA, LORE_LIBRARY_BIOMES, LORE_LIBRARY_STRUCTURES_AND_LOCATIONS, LORE_LIBRARY_WORLD_GEO } from './environment';
import { LORE_LIBRARY_WEAPONS, LORE_LIBRARY_PROFESSIONS, LORE_LIBRARY_FOOD_AND_DRINKS, LORE_LIBRARY_MARTIAL_ARTS_CONCEPTS, LORE_LIBRARY_MARTIAL_ARTS_KIM_DUNG } from './genre';
import { LORE_LIBRARY_INSTRUMENTS } from './instruments';
import { LORE_LIBRARY_FANTASY_MATERIALS } from './materials';
import { LORE_LIBRARY_VEHICLES, LORE_LIBRARY_FIREARMS, LORE_LIBRARY_AMMUNITION, LORE_LIBRARY_MODERN_NATIONS, LORE_LIBRARY_CORPORATIONS, LORE_LIBRARY_MODERN_LIFESTYLE, LORE_LIBRARY_MODERN_SPORTS, LORE_LIBRARY_COSPLAY, LORE_LIBRARY_BOARD_AND_CARD_GAMES, LORE_LIBRARY_MODERN_MACHINERY } from './modern';
import { LORE_LIBRARY_ACCESSORIES, LORE_LIBRARY_EYEWEAR_AND_VISION } from './accessories';
import { LORE_LIBRARY_COMPETITIONS } from './competitions';
import { LORE_LIBRARY_COMMUNICATION } from './communication';
import { LORE_LIBRARY_ASSETS, LORE_LIBRARY_MODERN_RARITY } from './assets';
import { LORE_LIBRARY_PARTIES } from './parties';
// FIX: Export individual constants to allow re-exporting from other modules.
import { LORE_LIBRARY_ADULT_ITEMS, LORE_LIBRARY_SEX_LOCATIONS, LORE_LIBRARY_SEXUAL_SCENARIOS, LORE_LIBRARY_FOREPLAY, LORE_LIBRARY_INTERCOURSE, LORE_LIBRARY_FEMALE_ORGASM, LORE_LIBRARY_MALE_ORGASM, LORE_LIBRARY_AFTERCARE, LORE_LIBRARY_KISSING, LORE_LIBRARY_CUDDLING_AND_TOUCHING, LORE_LIBRARY_ORAL_SEX, LORE_LIBRARY_RELATIONSHIP_TERMS } from './adult';
import { LORE_LIBRARY_MODERN_COMBAT } from './modern-combat';
import { LORE_LIBRARY_HISTORICAL_BATTLES } from './historical-battles';
import { LORE_LIBRARY_HISTORICAL_BEAUTIES, LORE_LIBRARY_GODDESSES } from './historical-figures';
import { LORE_LIBRARY_FIRE_MAKING, LORE_LIBRARY_COOKING_METHODS_AND_TOOLS } from './technology';
import { LORE_LIBRARY_HUNTING_METHODS_AND_TOOLS, LORE_LIBRARY_TRAPPING_METHODS } from './survival';
import { LORE_LIBRARY_COSMOLOGY_AND_ASTRONOMY } from './space';
import { LORE_LIBRARY_COSMOLOGY_XIANXIA, LORE_LIBRARY_PROFOUND_CONCEPTS_XIANXIA, LORE_LIBRARY_BODY_CULTIVATION } from './cultivation_concepts';
import { LORE_LIBRARY_FORMS_OF_ADDRESS, LORE_LIBRARY_HIERARCHIES, LORE_LIBRARY_AWARDS_AND_HONORS } from './social';
import { LORE_LIBRARY_CONFLICT_AND_CALAMITY } from './conflict';
import { LORE_LIBRARY_ONE_PIECE, LORE_LIBRARY_NARUTO, LORE_LIBRARY_MECHA, LORE_LIBRARY_SUPERHEROES_MARVEL_DC, LORE_LIBRARY_MONSTER_TAMING, LORE_LIBRARY_HARRY_POTTER, LORE_LIBRARY_TRANSFORMERS, LORE_LIBRARY_SHAMAN_KING } from './ip';

// --- Nhom Thu vien ve Ngoai hinh & Nhan vat ---
const LORE_LIBRARIES_APPEARANCE = `
### LORE GROUP: APPEARANCE & CHARACTER DESCRIPTION ###
${LORE_LIBRARY_ATTIRE}
${LORE_LIBRARY_HUMAN_DESCRIPTION}
${LORE_LIBRARY_ACCESSORIES}
${LORE_LIBRARY_HAIR}
${LORE_LIBRARY_EYEWEAR_AND_VISION}
${LORE_LIBRARY_AGING_APPEARANCE}
`;

// --- Nhom Thu vien ve Con nguoi & Than thoai ---
const LORE_LIBRARIES_PEOPLE = `
### LORE GROUP: PEOPLE & MYTHOLOGY ###
${LORE_LIBRARY_HISTORICAL_BEAUTIES}
${LORE_LIBRARY_GODDESSES}
`;

// --- Nhom Thu vien ve Tuong tac Xa hoi ---
const LORE_LIBRARIES_SOCIAL = `
### LORE GROUP: SOCIAL INTERACTION & CULTURE ###
${LORE_LIBRARY_FORMS_OF_ADDRESS}
${LORE_LIBRARY_HIERARCHIES}
${LORE_LIBRARY_AWARDS_AND_HONORS}
`;

// --- Nhom Thu vien ve The gioi Hien dai ---
const LORE_LIBRARIES_MODERN = `
### LORE GROUP: MODERN WORLD & TECHNOLOGY ###
${LORE_LIBRARY_VEHICLES}
${LORE_LIBRARY_FIREARMS}
${LORE_LIBRARY_AMMUNITION}
${LORE_LIBRARY_MODERN_NATIONS}
${LORE_LIBRARY_CORPORATIONS}
${LORE_LIBRARY_MODERN_LIFESTYLE}
${LORE_LIBRARY_MODERN_SPORTS}
${LORE_LIBRARY_COSPLAY}
${LORE_LIBRARY_BOARD_AND_CARD_GAMES}
${LORE_LIBRARY_MODERN_MACHINERY}
`;

// --- Nhom Thu vien The loai Cu the (Fantasy, Vo lam, etc.) ---
const LORE_LIBRARIES_GENRE_SPECIFIC = `
### LORE GROUP: GENRE-SPECIFIC (WEAPONS, PROFESSIONS, ITEMS) ###
${LORE_LIBRARY_WEAPONS}
${LORE_LIBRARY_PROFESSIONS}
${LORE_LIBRARY_FANTASY_MATERIALS}
${LORE_LIBRARY_FOOD_AND_DRINKS}
${LORE_LIBRARY_INSTRUMENTS}
${LORE_LIBRARY_MARTIAL_ARTS_CONCEPTS}
${LORE_LIBRARY_MARTIAL_ARTS_KIM_DUNG}
${LORE_LIBRARY_MODERN_COMBAT}
${LORE_LIBRARY_COSMOLOGY_XIANXIA}
${LORE_LIBRARY_PROFOUND_CONCEPTS_XIANXIA}
${LORE_LIBRARY_BODY_CULTIVATION}
`;

// --- Nhom Thu vien ve Moi truong & Thien nhien ---
const LORE_LIBRARIES_ENVIRONMENT = `
### LORE GROUP: ENVIRONMENT, NATURE & LOCATIONS ###
${LORE_LIBRARY_ASTRONOMICAL_PHENOMENA}
${LORE_LIBRARY_BIOMES}
${LORE_LIBRARY_STRUCTURES_AND_LOCATIONS}
${LORE_LIBRARY_WORLD_GEO}
${LORE_LIBRARY_COSMOLOGY_AND_ASTRONOMY}
`;

// --- Nhom Thu vien ve Cong nghe & Sinh ton ---
const LORE_LIBRARIES_TECHNOLOGY_AND_SURVIVAL = `
### LORE GROUP: TECHNOLOGY & SURVIVAL ###
${LORE_LIBRARY_FIRE_MAKING}
${LORE_LIBRARY_COOKING_METHODS_AND_TOOLS}
${LORE_LIBRARY_HUNTING_METHODS_AND_TOOLS}
${LORE_LIBRARY_TRAPPING_METHODS}
`;


// --- Nhom Thu vien ve Su kien & Hoat dong ---
const LORE_LIBRARIES_EVENTS = `
### LORE GROUP: EVENTS, ACTIVITIES & COMPETITIONS ###
${LORE_LIBRARY_COMPETITIONS}
${LORE_LIBRARY_PARTIES}
`;

// --- Nhom Thu vien ve Giao tiep & Thong tin ---
const LORE_LIBRARIES_COMMUNICATION = `
### LORE GROUP: COMMUNICATION & INFORMATION ###
${LORE_LIBRARY_COMMUNICATION}
`;

// --- Nhom Thu vien ve Kinh te & Tai san ---
const LORE_LIBRARIES_ECONOMY = `
### LORE GROUP: ECONOMY & ASSETS ###
${LORE_LIBRARY_ASSETS}
${LORE_LIBRARY_MODERN_RARITY}
`;

// --- Nhom Thu vien ve Chu de Nguoi lon (18+) ---
const LORE_LIBRARIES_ADULT = `
### LORE GROUP: ADULT THEMES & ITEMS (18+) ###
${LORE_LIBRARY_ADULT_ITEMS}
${LORE_LIBRARY_SEX_LOCATIONS}
${LORE_LIBRARY_SEXUAL_SCENARIOS}
${LORE_LIBRARY_FOREPLAY}
${LORE_LIBRARY_INTERCOURSE}
${LORE_LIBRARY_FEMALE_ORGASM}
${LORE_LIBRARY_MALE_ORGASM}
${LORE_LIBRARY_AFTERCARE}
${LORE_LIBRARY_KISSING}
${LORE_LIBRARY_CUDDLING_AND_TOUCHING}
${LORE_LIBRARY_ORAL_SEX}
${LORE_LIBRARY_RELATIONSHIP_TERMS}
`;

// --- Nhom Thu vien ve Lich su & Chien tranh ---
const LORE_LIBRARIES_HISTORY = `
### LORE GROUP: HISTORY & WARFARE ###
${LORE_LIBRARY_HISTORICAL_BATTLES}
`;

// NEW: Nhom Thu vien ve Xung dot & Tai uong
const LORE_LIBRARIES_CONFLICT = `
### LORE GROUP: CONFLICT & CALAMITY ###
${LORE_LIBRARY_CONFLICT_AND_CALAMITY}
`;

// NEW: Nhom Thu vien ve cac IP noi tieng
const LORE_LIBRARIES_IP = `
### LORE GROUP: NỔI TIẾNG (FAMOUS IPs) ###
${LORE_LIBRARY_ONE_PIECE}
${LORE_LIBRARY_NARUTO}
${LORE_LIBRARY_MECHA}
${LORE_LIBRARY_SUPERHEROES_MARVEL_DC}
${LORE_LIBRARY_MONSTER_TAMING}
${LORE_LIBRARY_HARRY_POTTER}
${LORE_LIBRARY_TRANSFORMERS}
${LORE_LIBRARY_SHAMAN_KING}
`;

// =================================================================
// FINAL EXPORTED LIBRARY
// This constant assembles all the grouped libraries into a single block
// for the AI to consume.
// =================================================================
export const WORLD_BUILDING_LIBRARIES = `
${LORE_LIBRARIES_APPEARANCE}
${LORE_LIBRARIES_PEOPLE}
${LORE_LIBRARIES_MODERN}
${LORE_LIBRARIES_GENRE_SPECIFIC}
${LORE_LIBRARIES_ENVIRONMENT}
${LORE_LIBRARIES_TECHNOLOGY_AND_SURVIVAL}
${LORE_LIBRARIES_EVENTS}
${LORE_LIBRARIES_COMMUNICATION}
${LORE_LIBRARIES_ECONOMY}
${LORE_LIBRARIES_ADULT}
${LORE_LIBRARIES_HISTORY}
${LORE_LIBRARIES_SOCIAL}
${LORE_LIBRARIES_CONFLICT}
${LORE_LIBRARIES_IP}
`;
